name: Publish Docker Image
on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USER: swchck
  REPO_NAME: transcriber
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: whisper
            app_name: whisper
          - context: webui
            app_name: transcriber-web
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/transcriber/${{ matrix.app_name }}:latest
          no-cache: true